name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
      - name: Build project
        run: cabal build --enable-tests
      - name: Run tests
        run: cabal test all --test-show-details=direct
        env:
          HSPEC_OPTIONS: --color
  success:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - run: echo success