# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10.3' # Exact version of ghc to use
          enable-stack: true
          stack-version: 'latest'
      - name: Install dependencies
        run: stack test


  success:
    needs: [build]
    runs-on: ubuntu-latest
    steps: [run: echo success]